# This is a basic workflow to help you get started with Actions

name: Build Squid image

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Set some variables for the build
    env:
      IMAGE_NAME: ghcr.io/twosigma/docker-squid4
      REGISTRY_USERNAME: scottrich 
      TAG: ${{ github.sha }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Artifact Registry
        run: echo ${{ secrets.REGISTRY_ACCESS_TOKEN }} | docker login ghcr.io -u $REGISTRY_USERNAME --password-stdin

      - name: Get the version
        id: vars
        run: echo Building $IMAGE_NAME:$TAG as $REGISTRY_USERNAME
        
      - name: Build and tag the Docker image
        run: |
          cd docker-squid
          docker build . --file Dockerfile --tag $IMAGE_NAME:$TAG --tag $IMAGE_NAME:latest --cache-from $IMAGE_NAME:latest
          
      - name: Push the new Docker image
        run: |
          docker push $IMAGE_NAME:$TAG
          docker push $IMAGE_NAME:latest
          
